name: Deploy to Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/checkout@v3
      with:
        ref: dist
        path: dist
    - name: Clear old deploy
      run: |
        rm -r dist/assets/
    - name: Use Node.js 16.15.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Deploy to Pages
      run: |
        cd dist
        git config user.name 'Automated Deployment'
        git config user.email 'aidan@trifuse.xyz'
        git add .
        git commit -m 'Deploy to Pages'
        git push