name: Deploy to Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        ref: dist
    - name: Clear old deploy
      run: rm -rf dist/*
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Deploy to Pages
      run: |
        git config user.name 'Automated Deployment'
        git config user.email 'aidan@trifuse.xyz'
        git add .
        git commit -m 'Deploy to Pages'
        git push